import Head from "next/head";
import { useEffect, useRef } from "react";
import styles from "../styles/Home.module.css";
import { v4 as uuidv4 } from "uuid";
import crypto from "crypto";
import { GetStaticProps } from "next";
type HomeProps = {
  randomRoomId: string;
};

export default function Home(homeProps: HomeProps) {
  const idInput = useRef<HTMLInputElement>(null);
  useEffect(() => {
    if (!idInput.current) return;
    console.log(idInput.current.placeholder);

    var type_this = homeProps.randomRoomId;
    var index = 0;

    const next_letter = function () {
      if (index <= type_this.length) {
        idInput.current!.placeholder = type_this.substr(0, index++);
        setTimeout(() => {
          next_letter();
        }, 100);
      }
    };
    next_letter();
  }, [idInput.current]);
  return (
    <div className={styles.container}>
      <Head>
        <title>SWATEK MEET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full w-full grid grid-cols-1 grid-rows-homeGrid">
        <div className="bg-home-bg bg-cover bg-no-repeat shadow-2xl">
          <div className="h-full w-full bg-gradient-to-r from-gray-900 flex flex-col justify-between">
            <a href="https://www.swatek.tn/">
              <img
                src="swatek.svg"
                className="w-60 h-32 py-3 hover:cursor-pointer"
              />
            </a>
            <p className="p-7 text-center text-white font-thin text-3xl">
              Start & join meetings{" "}
            </p>
          </div>
        </div>
        <div>
          <div className="flex justify-center items-center h-full">
            <input
              className="outline-none transition border-2 border-gray-500 rounded-lg p-2 focus:border-blue-500"
              type="text"
              ref={idInput}
              placeholder=""
            />
            <button className="transition duration-500 m-2 p-2 px-3 border-solid border-2 border-blue-500 rounded-lg hover:text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600 focus:ring-opacity-50">
              Join
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  // const randomRoomId = uuidv4();
  const randomRoomId = crypto.randomBytes(8).toString("hex");
  return {
    props: { randomRoomId },
  };
};
