import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SWATEK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-full w-full grid grid-cols-1 grid-rows-homeGrid">
        <div className="bg-home-bg bg-cover bg-no-repeat">
          <div className="h-full w-full bg-gradient-to-r from-gray-900 flex flex-col justify-between">
            <h1 className="text-white font-bold text-3xl p-5">SWATEK</h1>
            <p className="p-7 text-center text-white font-thin text-3xl">
              Start & join meetings{" "}
            </p>
          </div>
        </div>
        <div>
          <div className="flex justify-center items-center h-full">
            <input
              className="outline-none transition border-2 border-gray-500 rounded-lg p-2 focus:border-blue-500"
              type="text"
            />
            <button className="transition m-2 p-2 px-3 border-solid border-2 border-blue-500 rounded-lg hover:text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600 focus:ring-opacity-50">
              Wiow
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
